if(EXISTS "/home/jica/repo/Bachata-S4/build-tests/tests/shadps4_bachata_runtime_test[1]_tests.cmake")
  include("/home/jica/repo/Bachata-S4/build-tests/tests/shadps4_bachata_runtime_test[1]_tests.cmake")
else()
  add_test(shadps4_bachata_runtime_test_NOT_BUILT shadps4_bachata_runtime_test_NOT_BUILT)
endif()
